import type { CloudinaryFolder } from "./cloudinary";

export const VISIBILITY_VALUES=["private","admins","members","public"] as const;
export type Visibility=typeof VISIBILITY_VALUES[number];
export type Viewer={id:string;roles:string[];status:string}|null;
export function isAdmin(viewer:Viewer){return Boolean(viewer?.roles.some(r=>["admin","super_admin"].includes(r)))}
export function canSee(level:Visibility|undefined,viewer:Viewer,ownerId:string){if(viewer?.id===ownerId||isAdmin(viewer))return true;if(level==="public")return true;if(level==="members")return viewer?.status==="verified";return false}
export function completionScore(profile:Record<string,unknown>){const checks=[profile.profileImage,profile.fullName,profile.house,profile.occupation,profile.bio,profile.city,profile.country,profile.schoolMemory,Array.isArray(profile.skills)&&profile.skills.length,profile.phone||profile.website];return Math.round(checks.filter(Boolean).length/checks.length*100)}
export function splitList(value:unknown,max=12){if(!Array.isArray(value))return[];return value.map(String).map(v=>v.trim()).filter(Boolean).slice(0,max)}
export function publicProfileDTO(profile:any,user:any,viewer:Viewer){const ownerId=String(user._id);const v=profile.visibility||{};const base:any={id:ownerId,fullName:profile.fullName,nickname:profile.nickname,profileImage:profile.profileImage,house:profile.house,classArm:profile.classArm,graduationYear:profile.graduationYear,professionalSummary:profile.professionalSummary,bio:profile.bio,skills:profile.skills||[],schoolMemory:profile.schoolMemory,interests:profile.interests||[],moderationStatus:profile.moderationStatus,completionScore:profile.completionScore||0,updatedAt:profile.updatedAt};if(canSee(v.location,viewer,ownerId)){base.city=profile.city;base.region=profile.region;base.country=profile.country}if(canSee(v.occupation,viewer,ownerId)){base.occupation=profile.occupation;base.industry=profile.industry}if(canSee(v.employer,viewer,ownerId))base.employer=profile.employer;if(canSee(v.email,viewer,ownerId))base.email=user.email;if(canSee(v.phone,viewer,ownerId))base.phone=profile.phone;if(canSee(v.whatsapp,viewer,ownerId))base.whatsapp=profile.whatsapp;if(canSee(v.birthday,viewer,ownerId))base.birthday=profile.birthday;if(canSee(v.socialLinks,viewer,ownerId))base.socialLinks=profile.socialLinks;if(canSee(v.business,viewer,ownerId))base.business=profile.business;if(canSee(v.education,viewer,ownerId))base.education=profile.education;if(canSee(v.achievements,viewer,ownerId))base.achievements=profile.achievements;if(viewer?.id===ownerId||isAdmin(viewer)){base.visibility=v;base.website=profile.website;base.moderationNote=profile.moderationNote;base.profileImagePublicId=profile.profileImagePublicId}return base}
