import { NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { z } from "zod";
import { connectToDatabase } from "@/lib/mongodb";
import { assertSameOrigin, createOpaqueToken, hashToken } from "@/lib/auth";
import { sendAuthEmail } from "@/lib/email";
import { rateLimit, requestKey } from "@/lib/rate-limit";
import { User } from "@/models/User";
import { MemberProfile } from "@/models/MemberProfile";
import { AuthToken } from "@/models/AuthToken";

const schema=z.object({name:z.string().trim().min(3).max(100),nickname:z.string().trim().max(60).optional(),email:z.string().email().transform(v=>v.toLowerCase()),house:z.string().trim().min(2).max(40),password:z.string().min(10).max(128).regex(/[A-Z]/,"Include an uppercase letter").regex(/[a-z]/,"Include a lowercase letter").regex(/[0-9]/,"Include a number")});
export async function POST(request:Request){try{await assertSameOrigin(request);if(!rateLimit(requestKey(request,"register"),5))return NextResponse.json({error:"Too many registration attempts. Try again later."},{status:429});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Check your details."},{status:400});await connectToDatabase();const {name,nickname,email,house,password}=parsed.data;if(await User.exists({email}))return NextResponse.json({error:"An account already exists for this email."},{status:409});const isBootstrap=email===process.env.BOOTSTRAP_ADMIN_EMAIL?.toLowerCase();const user=await User.create({name,nickname,email,house,passwordHash:await bcrypt.hash(password,12),roles:isBootstrap?["member","super_admin"]:["member"],status:isBootstrap?"verified":"pending",emailVerifiedAt:isBootstrap?new Date():undefined,approvedAt:isBootstrap?new Date():undefined});await MemberProfile.create({userId:user._id,fullName:name,nickname,house,graduationYear:2012,visibility:{profile:"members"}});if(isBootstrap)return NextResponse.json({message:"Super administrator account created. You can sign in.",login:true});const token=createOpaqueToken();await AuthToken.deleteMany({userId:user._id,purpose:"verify_email"});await AuthToken.create({tokenHash:hashToken(token),userId:user._id,purpose:"verify_email",expiresAt:new Date(Date.now()+24*60*60*1000)});const base=process.env.NEXT_PUBLIC_APP_URL||new URL(request.url).origin;const result=await sendAuthEmail({to:email,name,url:`${base}/verify-email?token=${encodeURIComponent(token)}`,purpose:"verify"});return NextResponse.json({message:"Check your email to verify your address.",developmentUrl:result.developmentUrl})}catch(error){console.error("Registration failed",error);return NextResponse.json({error:"We could not create your account. Please try again."},{status:500})}}
