"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useState } from "react";
import { ArrowRight, AlertCircle, Eye, EyeOff, LoaderCircle, ShieldCheck } from "lucide-react";
import SiteHeader from "@/components/site-header";

function LoginForm() { const router = useRouter(), params = useSearchParams(); const [loading, setLoading] = useState(false), [error, setError] = useState(""), [showPassword, setShowPassword] = useState(false); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(""); const form = new FormData(e.currentTarget); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const requested = params.get("next"); router.push(requested?.startsWith("/") ? requested : data.redirectTo); router.refresh() } catch (e) { setError(e instanceof Error ? e.message : "Sign in failed."); setLoading(false) } } return <form className="auth-box" onSubmit={submit}><span className="eyebrow">Members area</span><h2>Welcome back</h2><p>Sign in with your verified member account.</p>{error && <div className="form-alert error"><AlertCircle size={16} />{error}</div>}<div className="form-group"><label htmlFor="email">Email address</label><input className="input" id="email" name="email" type="email" autoComplete="email" required placeholder="you@example.com" /></div><div className="form-group"><label htmlFor="password">Password</label><div style={{ position: "relative" }}><input className="input" id="password" name="password" type={showPassword ? "text" : "password"} autoComplete="current-password" required placeholder="Enter your password" style={{ paddingRight: 42 }} /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(v => !v)} style={{ position: "absolute", right: 10, top: "50%", transform: "translateY(-50%)", border: 0, background: "transparent", color: "#637083", padding: 0, display: "grid", placeItems: "center" }}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></div><div className="form-line"><label><input type="checkbox" /> Remember me</label><Link href="/forgot-password">Forgot password?</Link></div><button className="btn btn-navy" disabled={loading}>{loading ? <LoaderCircle className="spin" size={17} /> : <ShieldCheck size={17} />} {loading ? "Signing in…" : "Sign in securely"} <ArrowRight size={16} /></button><p className="auth-switch">Not yet in the directory? <Link href="/register">Request membership</Link></p></form> }
export default function Login() { return <><SiteHeader /><main className="auth-page"><section className="auth-visual"><div><span className="eyebrow">Welcome home, brother</span><h1>Your community is only a sign-in away.</h1><p>Access the private directory, RSVP for events, manage your profile and stay close to the brothers who shared the Mount with you.</p></div></section><section className="auth-form-wrap"><Suspense><LoginForm /></Suspense></section></main></> }
