"use client";
import { useRef, useState } from "react";
import { CheckCircle2, CloudUpload, ImageIcon, LoaderCircle, Trash2, XCircle } from "lucide-react";
import type { CloudinaryFolder } from "@/lib/cloudinary";

type Asset = { publicId:string; secureUrl:string; width:number; height:number; format:string; bytes:number };
const MAX_BYTES=10*1024*1024, ACCEPTED=["image/jpeg","image/png","image/webp","image/avif"];
export default function CloudinaryUploader({folder="gallery",onUploaded}:{folder?:CloudinaryFolder;onUploaded?:(asset:Asset)=>void}){
 const inputRef=useRef<HTMLInputElement>(null); const [dragging,setDragging]=useState(false); const [progress,setProgress]=useState(0); const [status,setStatus]=useState<"idle"|"uploading"|"success"|"error">("idle"); const [error,setError]=useState(""); const [asset,setAsset]=useState<Asset|null>(null);
 async function upload(file?:File){if(!file)return;setError("");setAsset(null);if(!ACCEPTED.includes(file.type)){setStatus("error");setError("Choose a JPG, PNG, WebP or AVIF image.");return}if(file.size>MAX_BYTES){setStatus("error");setError("This image is larger than the 10 MB limit.");return}setStatus("uploading");setProgress(3);try{const response=await fetch("/api/cloudinary/signature",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({folder})});const signed=await response.json();if(!response.ok)throw new Error(signed.error||"Could not authorise the upload.");const data=new FormData();data.append("file",file);data.append("api_key",signed.apiKey);data.append("timestamp",String(signed.timestamp));data.append("signature",signed.signature);data.append("folder",signed.folder);data.append("allowed_formats",signed.allowedFormats);data.append("unique_filename","true");data.append("use_filename","false");const result=await new Promise<Record<string,unknown>>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST",`https://api.cloudinary.com/v1_1/${signed.cloudName}/image/upload`);xhr.upload.onprogress=e=>e.lengthComputable&&setProgress(Math.round(e.loaded/e.total*100));xhr.onerror=()=>reject(new Error("Network error while uploading."));xhr.onload=()=>{const body=JSON.parse(xhr.responseText||"{}");xhr.status>=200&&xhr.status<300?resolve(body):reject(new Error(body.error?.message||"Cloudinary rejected the upload."))};xhr.send(data)});const uploaded={publicId:String(result.public_id),secureUrl:String(result.secure_url),width:Number(result.width),height:Number(result.height),format:String(result.format),bytes:Number(result.bytes)};setAsset(uploaded);setStatus("success");setProgress(100);onUploaded?.(uploaded)}catch(e){setStatus("error");setError(e instanceof Error?e.message:"Upload failed.");setProgress(0)}}
 function clear(){setAsset(null);setStatus("idle");setProgress(0);setError("");if(inputRef.current)inputRef.current.value=""}
 return <div className="upload-widget"><input ref={inputRef} type="file" hidden accept={ACCEPTED.join(",")} onChange={e=>upload(e.target.files?.[0])}/>{asset?<div className="upload-preview"><img src={asset.secureUrl} alt="Newly uploaded asset"/><div className="upload-preview-meta"><span className="upload-success"><CheckCircle2 size={16}/> Upload complete</span><h3>{asset.publicId.split("/").pop()}</h3><p>{asset.width} × {asset.height} · {asset.format.toUpperCase()} · {(asset.bytes/1024/1024).toFixed(2)} MB</p><button type="button" className="btn upload-remove" onClick={clear}><Trash2 size={15}/> Remove from form</button></div></div>:<button type="button" className={`upload-dropzone ${dragging?"dragging":""}`} onClick={()=>inputRef.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);upload(e.dataTransfer.files[0])}} disabled={status==="uploading"}><span className="upload-icon">{status==="uploading"?<LoaderCircle className="spin"/>:<CloudUpload/>}</span><strong>{status==="uploading"?`Uploading… ${progress}%`:"Drop an image here, or click to browse"}</strong><span>JPG, PNG, WebP or AVIF · Maximum 10 MB</span>{status==="uploading"&&<span className="progress-track"><i style={{width:`${progress}%`}}/></span>}</button>}{status==="error"&&<p className="upload-error"><XCircle size={15}/>{error}</p>}<p className="upload-note"><ImageIcon size={14}/> Images upload directly to the protected <b>{folder}</b> folder in Cloudinary.</p></div>
}
