import { NextResponse } from "next/server";
import { z } from "zod";
import { assertSameOrigin,getCurrentUser,hasAdminRole,hasContentRole } from "@/lib/auth";
import { slugify } from "@/lib/content";
import { connectToDatabase } from "@/lib/mongodb";
import { recordPublication } from "@/lib/publishing";
import { Event } from "@/models/Event";
import { Rsvp } from "@/models/Rsvp";
const schema=z.object({title:z.string().trim().min(5).max(160),summary:z.string().trim().min(10).max(350),description:z.string().trim().min(20).max(30000),startAt:z.string().min(1),endAt:z.string().optional(),timezone:z.string().default("Africa/Lagos"),venue:z.string().trim().max(200).optional(),mapUrl:z.string().url().or(z.literal("")).optional(),agenda:z.string().max(10000).optional(),dressCode:z.string().max(150).optional(),contactEmail:z.string().email().or(z.literal("")).optional(),capacity:z.number().int().min(0).max(10000).optional(),allowGuests:z.boolean(),maxGuests:z.number().int().min(0).max(10),visibility:z.enum(["public","members","admins"]),status:z.enum(["draft","review","scheduled","published","cancelled","completed","archived"]),featured:z.boolean(),coverImage:z.string().url().or(z.literal("")).optional(),coverImagePublicId:z.string().optional(),publishAt:z.string().optional()});
export async function GET(){const actor=await getCurrentUser();if(!hasContentRole(actor))return NextResponse.json({error:"Forbidden"},{status:403});await connectToDatabase();const events=await Event.find({}).sort({startAt:-1}).limit(200).lean() as any[];const counts=await Rsvp.aggregate([{$match:{response:"attending"}},{$group:{_id:"$eventId",members:{$sum:1},guests:{$sum:"$guestCount"}}}]),map=new Map(counts.map(c=>[String(c._id),c.members+c.guests]));return NextResponse.json({events:events.map(e=>({...e,attendeeCount:map.get(String(e._id))||0}))})}
export async function POST(request:Request){try{await assertSameOrigin(request);const actor=await getCurrentUser();if(!hasContentRole(actor))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Check the event."},{status:400});if(!hasAdminRole(actor)&&!["draft","review"].includes(parsed.data.status))return NextResponse.json({error:"Only administrators can publish or schedule."},{status:403});await connectToDatabase();const base=slugify(parsed.data.title)||"event";let slug=base,n=1;while(await Event.exists({slug}))slug=`${base}-${++n}`;const data:any={...parsed.data,slug,organiserId:actor!.id,lastEditorId:actor!.id,startAt:new Date(parsed.data.startAt),endAt:parsed.data.endAt?new Date(parsed.data.endAt):undefined,publishAt:parsed.data.publishAt?new Date(parsed.data.publishAt):undefined};if(data.endAt&&data.endAt<data.startAt)return NextResponse.json({error:"End time must be after start time."},{status:400});if(data.status==="published"){data.publishedAt=new Date();data.publishAt=data.publishAt||new Date();data.publishedBy=actor!.id}const event=await Event.create(data);await recordPublication({actorId:actor!.id,action:"event.created",entityType:"event",entity:event,notify:true});return NextResponse.json({message:"Event created.",event},{status:201})}catch(error){console.error(error);return NextResponse.json({error:"Unable to create event."},{status:500})}}
