import { NextResponse } from "next/server";
import { assertSameOrigin, getCurrentUser, hasAdminRole } from "@/lib/auth";
import { getCloudinaryConfig } from "@/lib/cloudinary";
import { connectToDatabase } from "@/lib/mongodb";
import { galleryPhotoInputSchema } from "@/lib/gallery";
import { GalleryPhoto } from "@/models/GalleryPhoto";

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{await assertSameOrigin(request);const actor=await getCurrentUser();if(!hasAdminRole(actor))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=galleryPhotoInputSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Check the photo details."},{status:400});await connectToDatabase();const {id}=await params;const photo=await GalleryPhoto.findById(id);if(!photo)return NextResponse.json({error:"Photo not found."},{status:404});const oldId=photo.imagePublicId;photo.set({...parsed.data,takenAt:parsed.data.takenAt?new Date(parsed.data.takenAt):undefined,credit:parsed.data.credit||undefined,updatedBy:actor!.id});await photo.save();if(oldId!==parsed.data.imagePublicId){const {cloudinary}=getCloudinaryConfig();await cloudinary.uploader.destroy(oldId,{invalidate:true});}return NextResponse.json({photo});}catch{return NextResponse.json({error:"Unable to update photo."},{status:500});}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{await assertSameOrigin(request);const actor=await getCurrentUser();if(!hasAdminRole(actor))return NextResponse.json({error:"Forbidden"},{status:403});await connectToDatabase();const {id}=await params;const photo=await GalleryPhoto.findByIdAndDelete(id);if(!photo)return NextResponse.json({error:"Photo not found."},{status:404});const {cloudinary}=getCloudinaryConfig();await cloudinary.uploader.destroy(photo.imagePublicId,{invalidate:true});return NextResponse.json({message:"Photo deleted."});}catch{return NextResponse.json({error:"Unable to delete photo."},{status:500});}}
